[package]
name = "shamir-secret-sharing"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
lazy_static = "1.4.0"
rand = "0.8.5"
ark-ff = "0.5.0"
ark-bn254 = "0.5.0"

[[bin]]
name = "prime_field_shamir"
path = "src/prime_field_shamir.rs"
